-- liquibase formatted sql

--changeset akupriyanov:1
CREATE TABLE card
(
    id BIGINT PRIMARY KEY,
    card_number BIGINT NOT NULL UNIQUE,
    cardholder_id BIGINT,--question
    data_active TIMESTAMP,
    status_card TEXT,
    card_balance DECIMAL(15,2) NOT NULL DEFAULT 0.00,
    PRIMARY KEY(id)
);

--changeset akupriyanov:2
CREATE TABLE client
(
    id BIGINT PRIMARY KEY,
    name VARCHAR(100),
    password VARCHAR(30),
    PRIMARY KEY(id)
);

--changeset akupriyanov:3
CREATE TABLE role
(
    id   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR NOT NULL UNIQUE,
);

--changeset akupriyanov:4
ALTER TABLE card
    ADD CONSTRAINT FK_client_card
    FOREIGN KEY (cardholder_id)
    REFERENCES client (id)
    ON DELETE CASCADE ON UPDATE CASCADE;

-- changeset akupriyanov:5
CREATE TABLE "clients_roles"
(
    client_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    PRIMARY KEY (client_id, role_id),
    FOREIGN KEY (client_id) REFERENCES client (id),
    FOREIGN KEY (role_id) REFERENCES roles (id)
);

INSERT INTO role (id, role)
VALUES (1, 'ADMIN'),
        (2, 'USER');