spring:
  application:
    name: www
  datasource:
    url: jdbc:postgresql://localhost:5432/BankSystemCardManagement
    username: student
    password: chocolatefrog
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        jakarta.persistence.access: field
        dialect: org.hibernate.dialect.PostgreSQLDialect
  liquibase:
    change-log: classpath:liquibase/changelog-master.yml

logging:
  level:
    root: info

server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    doc-expansion: none
    tags-sorter: alpha
    operations-sorter: method
    enabled: true
  api-docs:
    path: /api-docs
  default-produces-media-type: application/json
  security:
    jwt:
      header: "Authorization"
      prefix: "Bearer "
      secret_key: "4eeab38d706831be4b36612ead768ef8182d1dd6f0e14e5dc934652e297fb16a"
      access_token_expiration: 36000000 # 10 hours
      refresh_token_expiration: 252000000 # 7 days